version: '2'

services:
    consumer:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/consumer.php

    dashboard_consumer:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Dashboard/consumer.php

    purchase_consumer:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Purchase/consumer.php

    stock_consumer:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Stock/consumer.php

    stock_consume_once:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Stock/consume_once.php

    consume_once:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/consume_once.php
