version: '2'

services:
    projector:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/projector.php

    process_manager:
        extends:
            file: docker/templates.yml
            service: php-cli
        command: php src/Common/process_manager.php
